### ISSUE TITLE
Explicit source ~/.bahsrc

### ISSUE THREAD

**Issue by kranthik13** [aitoss/Youtube-Playlist-Downloader#5]
Everytime the install script is run 'youtube' is not activated.
For it to be activated explicit source ~/.bashrc is to be done.

**Comment by shellkore** [comment]
can you please assign this issue to me.

**Comment by shellkore** [comment]
issue solved in PR https://github.com/aitoss/youtube-downloader/pull/6

Please review it and merge so that I can claim my #GITSWAG

**Comment by kranthik13** [comment]
The issue also covers solving the problem of explicit "source ~/.bashrc".
I think it is still a problem.

**Comment by shellkore** [comment]
Since there is no use of bashrc file now.  you don't need to run source ~/.bashrc

**Comment by kranthik13** [comment]
Nice work! Closing this.

**Comment by kranthik13** [comment]
#GITSWAG +1
